config/routes.rb
Linkadex::Application.routes.draw do
  namespace :about do
    root :to => 'static_pages#index'
    namespace :tutorials do
      root :to => 'static_pages#index'
      get '/getting-started' => 'static_pages#getting_started', :as => 'getting_started'
      get '/creating-links' => 'static_pages#creating_links', :as => 'creating_links'
      get '/features' => 'static_pages#features', :as => 'features'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/users/:username' => 'users#groups_with_links'
    end
  end

  root :to => 'dashboard#home'

  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  resources :groups, :except => :show do
    post '/clone' => 'groups#clone_toggle', :on => :member
    post '/unclone' => 'groups#clone_toggle', :on => :member
    resources :links, :except => :show
    resources :comments, :except => :show
  end

  resources :colors, :except => :show do
    delete 'clean-up' => 'colors#clean_up', :as => 'clean_up', :on => :collection
  end

  resources :users do
    collection do
      get 'verify' => 'users#verify'
      get 'forgotten' => 'users#forgotten'
      put 'reset' => 'users#reset'
    end
  end

  scope '/:username', :as => 'friendly' do
    root :to => 'users#show', :as => 'user'
    get '/account' => 'users#edit', :as => 'edit_user'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_signed_in_user
  before_filter :load_groups

  def home
    @title = 'Dashboard - Linkadex'
  end

  private

    def load_groups
      @groups = current_user.groups.includes(:links).order(:collapsed, :title) + current_user.cloned_groups.includes(:links).order(:collapsed, :title)
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def current_clone?(group)
    current_user.groups.include?(group) || current_user.cloned_groups.include?(group)
  end

  def clone_button(group)
    (icon_for(current_clone?(group) ? 'eye-close' : 'eye-open') + " " + group.cloned_users.count.to_s).html_safe
  end

  def clone_link(group)
    current_clone?(group) ? unclone_group_path(group) : clone_group_path(group)
  end

  def clone_class(group)
    "btn #{current_clone?(group) ? 'active' : ''}"
  end

  def link_styles(link)
    "color: #{link.color.hex_value}; border: 0.3em solid #{link.border_color.hex_value}; background-color: #{link.background_color.hex_value}"
  end

  def show_group_as_link?(group, user)
    edit_mode? && current_user == group.user && (controller_name != 'users' && action_name != 'show' || current_user == user)
  end
end

app/views/dashboard/_group.html.haml
.row-fluid
  .group{ :id => "group#{group.id}", :style => "border: 0.2em solid #{group.color.hex_value}" }
    .pull-right
      - if signed_in?
        - if current_user != group.user
          - if current_user.cloned_groups.include?(group)
            = ("Cloned from " + (link_to group.user.name, friendly_user_path(group.user.username))).html_safe
          = link_to clone_button(group), clone_link(group), :remote => true, :class => clone_class(group), :id => "clone#{group.id}", :method => :post
        - elsif edit_mode? && controller_name != "users"
          = link_to icon_for(:plus), new_group_link_path(group, :destination => controller_name), :remote => true, :class => 'btn'
    %h2
      %span.collapse-toggle{ :data => { :collapsed => "#{group.collapsed?}" } }= icon_for(group.collapsed? ? 'plus-sign' : 'minus-sign')
      = show_group_as_link?(group, @user) ? (link_to group.title, group_links_path(group)) : group.title
      - if group.private?
        %span.private-icon{ :title => "Private Group" }= icon_for(:lock)
    .links{ :style => "#{group.collapsed? ? 'display: none' : ''}" }
      - group.links.order(:title).each do |link|
        = link_to link.title, link.href,
          :class => 'link',
          :id => "link#{link.id}",
          :target => '_' + link.target,
          :style => link_styles(link)
    .comments
      .pull-right
        = link_to icon_for(:comment), group_comments_path(group), :remote => signed_in?
        %span{ :id => "comment_count#{group.id}" }= group.comments.count
      %div{ :id => "comments_wrapper#{group.id}", :data => { :load => true.to_s } }
        %div{ :id => "comments#{group.id}" }
        %div{ :id => "comment_form#{group.id}" }

app/views/dashboard/home.html.haml
- if current_user.colors.empty?
  .alert.alert-notice
    Start using Linkadex by
    = link_to 'adding colors to your palette', colors_path
#home
  .groups
    = render :partial => 'group', :collection => @groups, :as => 'group'