config/routes.rb
Linkadex::Application.routes.draw do
  namespace :about do
    root :to => 'static_pages#index'
    namespace :tutorials do
      root :to => 'static_pages#index'
      get '/getting-started' => 'static_pages#getting_started', :as => 'getting_started'
      get '/creating-links' => 'static_pages#creating_links', :as => 'creating_links'
      get '/features' => 'static_pages#features', :as => 'features'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/users/:username' => 'users#groups_with_links'
    end
  end

  root :to => 'dashboard#home'

  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  resources :groups, :except => :show do
    post '/clone' => 'groups#clone_toggle', :on => :member
    post '/unclone' => 'groups#clone_toggle', :on => :member
    resources :links, :except => :show
    resources :comments, :except => :show
  end

  resources :colors, :except => :show do
    delete 'clean-up' => 'colors#clean_up', :as => 'clean_up', :on => :collection
  end

  resources :users do
    collection do
      get 'verify' => 'users#verify'
      get 'forgotten' => 'users#forgotten'
      put 'reset' => 'users#reset'
    end
  end

  scope '/:username', :as => 'friendly' do
    root :to => 'users#show', :as => 'user'
    get '/account' => 'users#edit', :as => 'edit_user'
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :links, :dependent => :destroy
  has_many :clones, :dependent => :destroy
  has_many :cloned_users, :through => :clones, :source => :user
  has_many :comments, :dependent => :destroy
  belongs_to :color
  belongs_to :user

  validates :user_id, :presence => true

  validates :color_id, :presence => true

  validates :title, :presence => true, :uniqueness => { :scope => :user_id }

  default_scope includes(:color).order(:order_rank, :title)
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :require_signed_in_user
  before_filter :load_colors, :only => [:new, :edit, :create, :update]

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.save
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    @group.assign_attributes(group_params)
    @group.save
    @group.clones.destroy_all if @group.private?
  end

  def index
    @title = 'Groups - Linkadex'
    @groups = current_user.groups
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
  end

  def clone_toggle
    @group = Group.find(params[:id])
    if !current_user.cloned_groups.include?(@group)
      Clone.create(:user_id => current_user.id, :group_id => @group.id) if !@group.private? && !current_user.groups.include?(@group)
    else
      Clone.find_by_user_id_and_group_id(current_user.id, @group.id).destroy
    end
  end

  private

    def group_params
      params.require(:group).permit(:title, :collapsed, :color_id, :order_rank, :private)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= render :partial => 'shared/form_header', :locals => { :object_name => 'Group' }
.modal-body
  = render :partial => 'shared/form_errors', :locals => { :object => @group }
  = form_for @group, :remote => true, :html => { :class => 'form-horizontal' } do |f|
    .control-group
      = f.label :title, :class => 'control-label'
      .controls
        = f.text_field :title
    .control-group
      = f.label :color_id, :class => 'control-label'
      .controls
        = render :partial => 'shared/color_select', :locals => { :name => :color_id, :color => @group.color, :f => f }
    .control-group
      = f.label :order_rank, :class => 'control-label'
      .controls
        = f.text_field :order_rank
    .control-group
      = f.label :collapsed, "Collapse?", :checked => @group.collapsed?, :class => 'control-label'
      .controls
        = f.check_box :collapsed
    .control-group
      = f.label :private, "Private?", :checked => @group.private?, :class => 'control-label'
      .controls
        = f.check_box :private
    .control-group
      .controls
        = f.submit "#{@verb} Group", :class => 'btn btn-primary'

app/views/groups/_group.html.haml
.group{ :id => "group#{group.id}", :style => "background-color: #{group.color.hex_value}" }
  .pull-right
    = link_to icon_for(:edit), edit_group_path(group), :remote => true
    = link_to icon_for(:remove), group_path(group), :method => :delete, :remote => true, :confirm => 'Delete group?'
  %h2= link_to group.title, group_links_path(group), :class => 'links'

app/views/groups/clone_toggle.js.erb
$("#group<%= escaped_id(@group) %>").replaceWith("<%= escape_javascript(render :partial => 'dashboard/group', :locals => { :group => @group }) %>");

app/views/groups/create.js.erb
<% if @group.valid? %>
  $("#modal").modal("hide");
  $("#groups").prepend("<%= escape_javascript(render @group) %>");
<% else %>
  $("#modal").html("<%= escape_javascript(render 'form') %>");
  <%= render 'shared/colorpicker' %>
<% end %>

app/views/groups/destroy.js.erb
$("#group<%= escape_javascript(@group.id.to_s) %>").fadeOut();

app/views/groups/index.html.haml
= link_to icon_for('plus-sign') + ' Create', new_group_path, :remote => true, :class => 'pull-right btn group-create'
%h1 Groups
#groups
  = render @groups

app/views/groups/new.js.erb
<% if current_user.colors.any? %>
  <%= render 'shared/show_modal' %>
<% else %>
  $("#groups").html('<div class="alert alert-error">Please add colors to your palette before creating a group!</div>');
<% end %>

app/views/groups/update.js.erb
<% if @group.valid? %>
  $("#modal").modal("hide");
  $("#group<%= escape_javascript(@group.id.to_s) %>").replaceWith("<%= escape_javascript(render @group) %>");
<% else %>
  $("#modal").html("<%= escape_javascript(render 'form') %>");
  <%= render 'shared/colorpicker' %>
<% end %>