config/routes.rb
Linkadex::Application.routes.draw do
  namespace :about do
    root :to => 'static_pages#index'
    namespace :tutorials do
      root :to => 'static_pages#index'
      get '/getting-started' => 'static_pages#getting_started', :as => 'getting_started'
      get '/creating-links' => 'static_pages#creating_links', :as => 'creating_links'
      get '/features' => 'static_pages#features', :as => 'features'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/users/:username' => 'users#groups_with_links'
    end
  end

  root :to => 'dashboard#home'

  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  resources :groups, :except => :show do
    post '/clone' => 'groups#clone_toggle', :on => :member
    post '/unclone' => 'groups#clone_toggle', :on => :member
    resources :links, :except => :show
    resources :comments, :except => :show
  end

  resources :colors, :except => :show do
    delete 'clean-up' => 'colors#clean_up', :as => 'clean_up', :on => :collection
  end

  resources :users do
    collection do
      get 'verify' => 'users#verify'
      get 'forgotten' => 'users#forgotten'
      put 'reset' => 'users#reset'
    end
  end

  scope '/:username', :as => 'friendly' do
    root :to => 'users#show', :as => 'user'
    get '/account' => 'users#edit', :as => 'edit_user'
  end
end

app/controllers/about/static_pages_controller.rb
module About
  class StaticPagesController < ApplicationController
    def index
      @title = 'About - Linkadex'
    end
  end
end

app/controllers/about/tutorials/static_pages_controller.rb
module About
  module Tutorials
    class StaticPagesController < ApplicationController
      def index
        @title = 'Tutorials - Linkadex'
      end

      def getting_started
        @title = 'Getting Started - Linkadex'
      end

      def creating_links
        @title = 'Creating Links - Linkadex'
      end

      def features
        @title = 'Features - Linkadex'
      end
    end
  end
end

app/helpers/about/static_pages_helper.rb
module About
  module StaticPagesHelper

  end
end

app/helpers/about/tutorials/static_pages_helper.rb
module About
  module Tutorials
    module StaticPagesHelper

    end
  end
end

app/views/about/tutorials/static_pages/creating_links.html.haml
%h1 Creating Links
%p
  Once you have signed in to your account you'll find yourself on the dashboard. You won't see anything here just yet, since you haven't created any links yet. First of all, click on the pencil in the top right corner of the page. This take you from
  %em normal mode
  into
  %em edit mode.
  From within edit mode, you can see a toolbar from which you can access all aspects of Linkadex.
%h2 Creating colors
%p The first thing you have to do to use Linkadex is create a color palette. Click on the Colors tab in the toolbar. This will take you to a page from which you can manage and personalize colors to be used for your bookmarks. Click on the Create button in the top right, and a dialog will come down. Create at least two colors by selecting a hex value and optional alias.
%h2 Creating groups
%p Click on the groups tab on the toolbar. From here you can create and manage groups, which are holders for your Linkadex bookmarks. Create one group for now by clicking on the Create button and specifying a title and selecting a color for the group.
%h2 Creating links
%p
  Click on the group you just created. This will take you to the group page. You won't see anything here right now, since you haven't created any links for the group. Create your first link by clicking on the Create button in the top right corner and specifying a title, color, border color, and background color. Now navigate back to
  = link_to 'your dashboard', root_path
  and check out your very first link in your very first group. All links and groups will be displayed in this manner and you can return to
  = link_to 'your color palette', colors_path
  to customize the appearance however you'd like.

app/views/about/tutorials/static_pages/features.html.haml
%h1 Features
%p Linkadex is still under heavy development, and new features are being added with every commit; stay tuned for a full list of things you can do with Linkadex.

app/views/about/tutorials/static_pages/getting_started.html.haml
%h1 Getting Started
%p
  To start using Linkadex, you must first
  = link_to "sign up for an account.", signup_path
  Enter a username, email address, your name, and choose a good password.
%h2 Verify your account
%p
  Once you have successfully signed up for a Linkadex account, you will be sent a verification email. You will not be able to access your account until it is verified. To do this, click on the link that was sent to your email address. After the verification step is complete, you can
  = link_to "sign in", signin_path
  with your email and password you chose while signing up.

app/views/about/tutorials/static_pages/index.html.haml
%h1 Tutorials
%ul
  %li= link_to 'Getting Started', about_tutorials_getting_started_path
  %li= link_to 'Creating Links', about_tutorials_creating_links_path
  %li= link_to 'Features', about_tutorials_features_path