config/routes.rb
Linkadex::Application.routes.draw do
  namespace :about do
    root :to => 'static_pages#index'
    namespace :tutorials do
      root :to => 'static_pages#index'
      get '/getting-started' => 'static_pages#getting_started', :as => 'getting_started'
      get '/creating-links' => 'static_pages#creating_links', :as => 'creating_links'
      get '/features' => 'static_pages#features', :as => 'features'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/users/:username' => 'users#groups_with_links'
    end
  end

  root :to => 'dashboard#home'

  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  resources :groups, :except => :show do
    post '/clone' => 'groups#clone_toggle', :on => :member
    post '/unclone' => 'groups#clone_toggle', :on => :member
    resources :links, :except => :show
    resources :comments, :except => :show
  end

  resources :colors, :except => :show do
    delete 'clean-up' => 'colors#clean_up', :as => 'clean_up', :on => :collection
  end

  resources :users do
    collection do
      get 'verify' => 'users#verify'
      get 'forgotten' => 'users#forgotten'
      put 'reset' => 'users#reset'
    end
  end

  scope '/:username', :as => 'friendly' do
    root :to => 'users#show', :as => 'user'
    get '/account' => 'users#edit', :as => 'edit_user'
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = favicon_link_tag
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if edit_mode?
      .container-fluid
        .navbar.navbar-static-top
          .navbar-inner
            = link_to 'Linkadex', root_path, :class => 'brand'
            %ul.nav
              %li.divider-vertical
              %li{ :class => controller_name == 'dashboard' ? 'active' : '' }= link_to 'Home', root_path(:mode => 'edit')
              %li{ :class => params[:controller].starts_with?('about') ? 'active' : '' }= link_to 'About', about_root_path
              - if signed_in?
                %li{ :class => controller_name == 'users' && action_name == 'index' ? 'active' : '' }= link_to 'Users', users_path
                %li.dropdown
                  = link_to 'Manage ▼', '#', :class => 'dropdown-toggle', :data => { :toggle => 'dropdown' }
                  %ul.dropdown-menu
                    %li= link_to 'My Groups', groups_path
                    %li= link_to 'My Colors', colors_path
              - else
                %li{ :class => controller_name == 'users' && action_name == 'new' ? 'active' : '' }= link_to 'Sign Up', signup_path
            %ul.nav.pull-right
              - if signed_in?
                %li.dropdown
                  = link_to current_user.name + ' ▼', '#', :class => 'dropdown-toggle', :data => { :toggle => 'dropdown' }
                  %ul.dropdown-menu
                    %li= link_to 'Account', friendly_edit_user_path(current_user.username)
                    %li= link_to 'Public Profile', friendly_user_path(current_user.username)
                - if controller_name == "dashboard"
                  %li.active= link_to icon_for(:pencil), root_path, :title => 'Toggle Edit Mode'
                %li= link_to icon_for(:off), signout_path, :title => 'Sign Out'
              - else
                %li{ :class => controller_name == 'sessions' && action_name == 'new' ? 'active' : '' }= link_to 'Sign in', signin_path
    - else
      .row-fluid#normal_wrapper
        .row-fluid#normal_menu
          .pull-right
            = link_to icon_for('resize-full'), "", :id => 'expand_all', :title => 'Expand All'
            &nbsp;&nbsp;
            = link_to icon_for('resize-small'), "", :id => 'collapse_all', :title => 'Collapse All'
            &nbsp;&nbsp;
            = link_to icon_for(:briefcase), friendly_edit_user_path(current_user.username), :title => 'Account'
            &nbsp;&nbsp;
            = link_to icon_for(:pencil), root_path(:mode => 'edit'), :title => 'Edit mode'
            &nbsp;&nbsp;
            = link_to icon_for(:off), signout_path, :title => 'Sign Out'
    .container-fluid
      #modal.modal.hide.fade{ :tabindex => '-1', :role => 'dialog', 'aria-laballedby' => 'modal_label', 'aria-hidden' => 'true', :data => { :backdrop => 'static' }}
      #flash.row-fluid
        .span12
      - flash.each do |type, message|
        .row-fluid
          .span12
            %div{ :class => "alert alert-#{type} flash" }= message
      .content{ :style => !edit_mode? ? "margin-top:1.5em;" : "margin-top:inherit;" }
        .row-fluid
          .span12
            = yield
      = debug params if Rails.env.development?